---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ag-deploy
  labels:
    app: ag-app
    test: test
#   annotations:
#     fluxcd.io/tag.example-app: semver:~1.0
#     fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: ag-app
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ag-app
    spec:
      containers:
      - name: ag-app
        image: ganeshmandava1247889/survey_extra_credit:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
