apiVersion: v1
kind: Service
metadata:
  name: swe645-service
  labels:
    app: swe645-app
spec:
  type: LoadBalancer
  selector:
    app: swe645-app
  ports:
    - protocol: TCP
      name: http
      port: 81
      targetPort: 4200
