# This is a basic workflow to help you get started with Actions

name: CI

on:
 
  push:
    branches: [ main ]

jobs:
 
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
           DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker login
        run: |
           cat ~/my_password.txt | docker login --username foo --password-stdin
      # Runs a single command using the runners shell
      - name: docker build
        run: |
          docker build . -t ganeshmandava1247889/survey_app
