# This is a basic workflow to help you get started with Actions

name: CI

on:
 
  push:
    branches: [ main ]

 
  workflow_dispatch:


jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: docker build
        run: |
          docker build . -t ganeshmandava1247889/survey_app
