# This is a basic workflow to help you get started with Actions

name: CI

on:
 
  push:
    branches: [ main ]

jobs:
 
  build:
    
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -  
         name: docker login
         env:
           DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         uses: docker/login-action@v1
         with:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
      # Runs a single command using the runners shell
      - name: docker build
        run: |
          docker build . -t ganeshmandava1247889/survey_app
